# Data Cleaning

Step of Data Cleaning:

    1. Load Dataset
    2. Handle missing values
    3. Handle duplicate values
    4. Clean and transform Datasets
    5. store clean dataset for next workflow steps

# Librairies

In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Load Data
Data ist stored as an Excel file. So, we use Pandas to load data

In [9]:
def load_data(file_path):
    data= pd.read_excel(
        file_path,
        engine='openpyxl',
        sheet_name=0
        )

    # komplett leere Spalten entfernen
    data = data.dropna(axis=1, how="all")
     # komplett leere Zeilen entfernen
    data = data.dropna(axis=0, how="all")

    return data

#file_path="../Data/usecarDataset.xlsx"
file_path="../../Data/used_cars_dataset.xlsx"

import os
#print("is path avaiable:",os.path.exists("../Data/usecarDataset.xlsx"))
data= load_data(file_path)
print(data.shape)
#print(data.head())
data.head(5)

(2541, 29)

,Brand,Model,year_of_manufacture,Engine_power(kilowatt),Engine_power_(Horsepower),Transmission_type,Mileage,Fueltype,nextTUV,Nber_previous_owners,...,damaged_tire,damaged_interior,damaged_rim,damaged_roof_beam,damaged_left_door,damaged_right_door,damaged_seats,interior_dirty,damaged_carosserie,images
0,Renault,Grand Scenic BLUE,2020,88,120,manuell,121323,Diesel,2025-11-01 00:00:00,2,...,1,1,1,1,0,0,1,1,1,A1
1,Renault,Grand Scenic BLUE,2020,88,120,manuell,149266,Diesel,2025-11-01 00:00:00,2,...,0,0,0,0,0,0,1,1,1,A2
2,Renault,Grand Scenic BLUE,2020,88,120,manuell,81943,Diesel,2027-07-01 00:00:00,2,...,1,1,0,1,0,0,1,0,1,A3
3,Renault,Grand Scenic BLUE,2020,88,120,manuell,19457,Diesel,2027-08-01 00:00:00,2,...,0,0,1,0,0,0,1,1,1,A4
4,Renault,Grand Scenic BLUE,2020,88,120,manuell,72400,Diesel,2025-11-01 00:00:00,1,...,1,1,0,1,1,0,1,1,1,A5

In [10]:
data.shape

(2541, 29)

In [11]:
print(data.dtypes)

Brand                        object
Model                        object
year_of_manufacture           int64
Engine_power(kilowatt)        int64
Engine_power_(Horsepower)     int64
Transmission_type            object
Mileage                       int64
Fueltype                     object
nextTUV                      object
Nber_previous_owners          int64
Body_style                   object
Tire_type                    object
Accident_history             object
Sale price                    int64
damaged_front                 int64
damaged_rear                  int64
damaged_left_side             int64
damaged_right_side            int64
damaged_exterior              int64
damaged_tire                  int64
damaged_interior              int64
damaged_rim                   int64
damaged_roof_beam             int64
damaged_left_door             int64
damaged_right_door            int64
damaged_seats                 int64
interior_dirty                int64
damaged_carosserie            int64
images                       object
dtype: object

In [12]:
print(data.columns)

Index(['Brand', 'Model', 'year_of_manufacture', 'Engine_power(kilowatt)',
       'Engine_power_(Horsepower)', 'Transmission_type', 'Mileage', 'Fueltype',
       'nextTUV', 'Nber_previous_owners', 'Body_style', 'Tire_type',
       'Accident_history', 'Sale price', 'damaged_front', 'damaged_rear',
       'damaged_left_side', 'damaged_right_side', 'damaged_exterior',
       'damaged_tire', 'damaged_interior', 'damaged_rim', 'damaged_roof_beam',
       'damaged_left_door', 'damaged_right_door', 'damaged_seats',
       'interior_dirty', 'damaged_carosserie', 'images'],
      dtype='object')

In [13]:
data.describe()

,year_of_manufacture,Engine_power(kilowatt),Engine_power_(Horsepower),Mileage,Nber_previous_owners,Sale price,damaged_front,damaged_rear,damaged_left_side,damaged_right_side,damaged_exterior,damaged_tire,damaged_interior,damaged_rim,damaged_roof_beam,damaged_left_door,damaged_right_door,damaged_seats,interior_dirty,damaged_carosserie
count,2541.000000,2541.000000,2541.000000,2541.000000,2541.000000,2541.000000,2541.000000,2541.000000,2541.000000,2541.000000,2541.000000,2541.000000,2541.000000,2541.000000,2541.000000,2541.000000,2541.000000,2541.000000,2541.000000,2541.000000
mean,2020.014955,138.223534,187.363243,122785.695789,1.972845,6827.296734,0.500984,0.485636,0.492719,0.500984,0.499016,0.510823,0.490752,0.500984,0.514364,0.517513,0.502952,0.523416,0.486029,0.508461
std,1.989681,46.962311,63.835744,70567.693746,0.811610,3587.081252,0.500097,0.499892,0.500045,0.500097,0.500097,0.499981,0.500013,0.500097,0.499892,0.499792,0.500090,0.499550,0.499903,0.500027
min,2016.000000,51.000000,69.000000,10.000000,1.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2018.000000,96.000000,130.000000,62255.000000,1.000000,3078.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2020.000000,137.000000,184.000000,120608.000000,2.000000,6243.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000
75%,2022.000000,180.000000,244.000000,182235.000000,3.000000,9200.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,2028.000000,220.000000,299.000000,249732.000000,3.000000,25845.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [14]:
data['nextTUV'] = pd.to_datetime(data['nextTUV'].str.strip(), dayfirst=True, errors='coerce')

In [15]:
print(data['nextTUV'].dtype)  # sollte datetime64[ns] sein
print(data['nextTUV'].head())
print(data['nextTUV'].isna().sum())  # wie viele NaT

datetime64[ns]
0   NaT
1   NaT
2   NaT
3   NaT
4   NaT
Name: nextTUV, dtype: datetime64[ns]
41

In [16]:
print(data['nextTUV'].unique()[:20])

<DatetimeArray>
[                'NaT', '2028-04-09 00:00:00', '2027-11-25 00:00:00',
 '2026-10-17 00:00:00', '2026-08-10 00:00:00', '2028-02-11 00:00:00',
 '2028-10-23 00:00:00', '2026-05-21 00:00:00', '2026-06-24 00:00:00',
 '2026-05-07 00:00:00', '2026-10-25 00:00:00', '2028-10-29 00:00:00',
 '2027-12-03 00:00:00', '2027-02-21 00:00:00', '2028-10-19 00:00:00',
 '2027-04-29 00:00:00', '2026-03-18 00:00:00', '2027-05-06 00:00:00',
 '2028-09-09 00:00:00', '2027-12-04 00:00:00']
Length: 20, dtype: datetime64[ns]

Modelle können Datetime nicht direkt verwenden. Deshalb wandeln wir es in Tage bis zum nächsten TÜV um:

In [17]:
#today = pd.Timestamp("2026-03-17")  # Referenzdatum
today = pd.Timestamp.today()


data['days_to_TUV'] = (data['nextTUV'] - today).dt.days
data.drop(columns=['nextTUV'], inplace=True)  # Datetime-Spalte entfernen

In [18]:
data['days_to_TUV'].head()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: days_to_TUV, dtype: float64

In [19]:
print(data.columns)
len(data)

Index(['Brand', 'Model', 'year_of_manufacture', 'Engine_power(kilowatt)',
       'Engine_power_(Horsepower)', 'Transmission_type', 'Mileage', 'Fueltype',
       'Nber_previous_owners', 'Body_style', 'Tire_type', 'Accident_history',
       'Sale price', 'damaged_front', 'damaged_rear', 'damaged_left_side',
       'damaged_right_side', 'damaged_exterior', 'damaged_tire',
       'damaged_interior', 'damaged_rim', 'damaged_roof_beam',
       'damaged_left_door', 'damaged_right_door', 'damaged_seats',
       'interior_dirty', 'damaged_carosserie', 'images', 'days_to_TUV'],
      dtype='object')

2541

In [20]:
print(data['Model'].unique())
data.shape

['Grand Scenic BLUE' 'Ford Focus' 'Nexo Fuel Cell Sports'
 'Kango rapid Blue' 'Focus' 'Fiesta' 'Traffic' 'loniq5' 'transit connect'
 'Doblo cargo' 'Tuscson' 'Cabrio Lounge' 'Clio' 'i30' 'Tucson' 'GLA'
 'Passat' 'A-Class' 'C-Class' 'Kuga' 'Megane' 'Golf' 'Kona' 'Captur'
 'Tiguan']

(2541, 29)

## Find Missing Value

In [21]:
data.isnull().sum().sort_values(ascending=False)

days_to_TUV                  41
damaged_left_side             0
images                        0
damaged_carosserie            0
interior_dirty                0
damaged_seats                 0
damaged_right_door            0
damaged_left_door             0
damaged_roof_beam             0
damaged_rim                   0
damaged_interior              0
damaged_tire                  0
damaged_exterior              0
damaged_right_side            0
Brand                         0
Model                         0
damaged_front                 0
Sale price                    0
Accident_history              0
Tire_type                     0
Body_style                    0
Nber_previous_owners          0
Fueltype                      0
Mileage                       0
Transmission_type             0
Engine_power_(Horsepower)     0
Engine_power(kilowatt)        0
year_of_manufacture           0
damaged_rear                  0
dtype: int64

First of all, we split test data for later analysis

In [22]:

x=data.drop(['Sale price'], axis=1)
y=data['Sale price']

x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.2, random_state=42)
data= x_train.copy()
data['Sale price']= y_train
print(data.isnull().sum())
#print(x.info())

Brand                         0
Model                         0
year_of_manufacture           0
Engine_power(kilowatt)        0
Engine_power_(Horsepower)     0
Transmission_type             0
Mileage                       0
Fueltype                      0
Nber_previous_owners          0
Body_style                    0
Tire_type                     0
Accident_history              0
damaged_front                 0
damaged_rear                  0
damaged_left_side             0
damaged_right_side            0
damaged_exterior              0
damaged_tire                  0
damaged_interior              0
damaged_rim                   0
damaged_roof_beam             0
damaged_left_door             0
damaged_right_door            0
damaged_seats                 0
interior_dirty                0
damaged_carosserie            0
images                        0
days_to_TUV                  38
Sale price                    0
dtype: int64

### Remove all missing value

In [23]:
# Remove all rows that have any missing values
data.dropna(inplace=True)

# Optional: reset index after dropping
data.reset_index(drop=True, inplace=True)

print(data.isnull().sum())

Brand                        0
Model                        0
year_of_manufacture          0
Engine_power(kilowatt)       0
Engine_power_(Horsepower)    0
Transmission_type            0
Mileage                      0
Fueltype                     0
Nber_previous_owners         0
Body_style                   0
Tire_type                    0
Accident_history             0
damaged_front                0
damaged_rear                 0
damaged_left_side            0
damaged_right_side           0
damaged_exterior             0
damaged_tire                 0
damaged_interior             0
damaged_rim                  0
damaged_roof_beam            0
damaged_left_door            0
damaged_right_door           0
damaged_seats                0
interior_dirty               0
damaged_carosserie           0
images                       0
days_to_TUV                  0
Sale price                   0
dtype: int64

In [24]:
print(data.dtypes)

Brand                         object
Model                         object
year_of_manufacture            int64
Engine_power(kilowatt)         int64
Engine_power_(Horsepower)      int64
Transmission_type             object
Mileage                        int64
Fueltype                      object
Nber_previous_owners           int64
Body_style                    object
Tire_type                     object
Accident_history              object
damaged_front                  int64
damaged_rear                   int64
damaged_left_side              int64
damaged_right_side             int64
damaged_exterior               int64
damaged_tire                   int64
damaged_interior               int64
damaged_rim                    int64
damaged_roof_beam              int64
damaged_left_door              int64
damaged_right_door             int64
damaged_seats                  int64
interior_dirty                 int64
damaged_carosserie             int64
images                        object
days_to_TUV                  float64
Sale price                     int64
dtype: object

In [25]:
#data.info

## Handle Duplicate Rows

In [26]:
duplicate_rows=data.duplicated()

if duplicate_rows.any():
    print(" There ist Duplicate rows")
    print(f"Number of duplicate rows: {duplicate_rows.sum()}")
    data= data.drop_duplicates()
else:
    print("No duplicate rows")
print(f"Shape of data after removing duplicates: {data.shape}")

No duplicate rows
Shape of data after removing duplicates: (1994, 29)

## Numerical Data check

In [27]:
numerical_cols= data.select_dtypes(include=['int64','float64' ]).columns.tolist()
print(data[numerical_cols].columns)
data[numerical_cols].describe()

Index(['year_of_manufacture', 'Engine_power(kilowatt)',
       'Engine_power_(Horsepower)', 'Mileage', 'Nber_previous_owners',
       'damaged_front', 'damaged_rear', 'damaged_left_side',
       'damaged_right_side', 'damaged_exterior', 'damaged_tire',
       'damaged_interior', 'damaged_rim', 'damaged_roof_beam',
       'damaged_left_door', 'damaged_right_door', 'damaged_seats',
       'interior_dirty', 'damaged_carosserie', 'days_to_TUV', 'Sale price'],
      dtype='object')

,year_of_manufacture,Engine_power(kilowatt),Engine_power_(Horsepower),Mileage,Nber_previous_owners,damaged_front,damaged_rear,damaged_left_side,damaged_right_side,damaged_exterior,...,damaged_interior,damaged_rim,damaged_roof_beam,damaged_left_door,damaged_right_door,damaged_seats,interior_dirty,damaged_carosserie,days_to_TUV,Sale price
count,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,...,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000
mean,2020.018556,138.376630,187.648445,123319.997994,1.986459,0.503009,0.483952,0.496991,0.499498,0.492979,...,0.479438,0.503009,0.519559,0.514544,0.512538,0.516048,0.490471,0.508526,378.613340,6811.778837
std,1.997780,46.901666,63.773214,70370.769396,0.812174,0.500116,0.499868,0.500116,0.500125,0.500076,...,0.499702,0.500116,0.499743,0.499914,0.499968,0.499868,0.500035,0.500053,294.104134,3594.744068
min,2017.000000,60.000000,81.000000,5020.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-118.000000,3000.000000
25%,2018.000000,97.000000,131.000000,63849.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,120.250000,3033.750000
50%,2020.000000,137.000000,186.000000,121303.500000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,380.500000,6195.000000
75%,2022.000000,180.000000,244.000000,183377.250000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,631.000000,9176.000000
max,2023.000000,220.000000,299.000000,249586.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,903.000000,20144.000000

## Categorical Sanity Check

I declare all categorical variables:

    . Brand and model
    . Fuel type
    . Transmission type
    . Trim level / Equipment line
    . Vehicle condition
    . Origin,
    . Category / Vehicle type
    . Color
    . Air conditioning / Climate control 
    . Transmission
    . Drive type
    . Interior equipment / Interior design 
    . Accident history
    . Maintenance / service history 
    . Inspection status (TÜV/HU)
    . Region / city 
    . Listing duration', 'Seller type', 'Body & paint',

In [28]:
#categorical_cols= data.select_dtypes(include=['object' ]).columns.tolist()
categorical_cols = data.select_dtypes(include=['object', 'category']).columns.tolist()
print(data[categorical_cols].columns)
data[categorical_cols].describe()

print( f"Length of categorical variable: {len(categorical_cols)} ")

Index(['Brand', 'Model', 'Transmission_type', 'Fueltype', 'Body_style',
       'Tire_type', 'Accident_history', 'images'],
      dtype='object')
Length of categorical variable: 8

#### Check an index of each rows

In [29]:
def cat_checker(catIndex):
    value= np.sort(data[categorical_cols[catIndex]].unique())
    return categorical_cols[catIndex], value

cat_checker(1)

('Model',
 array(['A-Class', 'C-Class', 'Captur', 'Clio', 'Fiesta', 'Focus', 'GLA',
        'Golf', 'Kona', 'Kuga', 'Megane', 'Passat', 'Tiguan', 'Tucson',
        'i30'], dtype=object))

## CHECKPOINT

In [30]:

%store data
%store numerical_cols
%store categorical_cols
%store x_test 
%store y_test

Stored 'data' (DataFrame)
Stored 'numerical_cols' (list)
Stored 'categorical_cols' (list)
Stored 'x_test' (DataFrame)
Stored 'y_test' (Series)