# Data Cleaning

Step of Data Cleaning:

    1. Load Dataset
    2. Handle missing values
    3. Handle duplicate values
    4. Clean and transform Datasets
    5. store clean dataset for next workflow steps

# Librairies

In [15]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Load Data
Data ist stored as an Excel file. So, we use Pandas to load data

In [16]:
def load_data(file_path):
    data= pd.read_excel(
        file_path,
        engine='openpyxl',
        sheet_name=0
        )

    # komplett leere Spalten entfernen
    data = data.dropna(axis=1, how="all")
     # komplett leere Zeilen entfernen
    data = data.dropna(axis=0, how="all")

    return data

file_path="../Data/useCarDaten.xlsx"
import os
print("is path avaiable:",os.path.exists("../Data/useCarDaten.xlsx"))
data= load_data(file_path)
print(data.shape)
#print(data.head())
data.head(7)

is path avaiable: True
(14, 69)

,Brand,Model,year of manufacture,Engine power (kilowatt),Engine power (Horsepower),Transmission type,Emission group,Cubic capacity,Number of gears,CO2 (g/km),...,space_saver_spare_wheel,has_headlight_washer,has_foldable_front_passenger_seat,has_warning_light,license_plate_holder,luggage_compartment_safety_net,has_height_adjustable_passenger_seat,has_foldable_seat_tables,has_advertising_foil,Unnamed: 13474
0,Renault,Grand Scenic BLUE,2020.0,88.0,120.0,manuell,AN,1750.0,6.0,142.0,...,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,NaN
1,Renault,Grand Scenic BLUE,2020.0,88.0,120.0,manuell,AN,1750.0,6.0,142.0,...,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,NaN
2,Renault,Grand Scenic BLUE,2020.0,88.0,120.0,manuell,AN,1750.0,6.0,142.0,...,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,NaN
3,Renault,Grand Scenic BLUE,2020.0,88.0,120.0,manuell,AN,1750.0,6.0,142.0,...,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,NaN
4,Renault,Grand Scenic BLUE,2020.0,88.0,120.0,manuell,AN,1750.0,6.0,142.0,...,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,NaN
5,Renault,Grand Scenic BLUE,2020.0,88.0,120.0,manuell,AN,1750.0,6.0,142.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,NaN
6,Ford,Ford Focus,2018.0,110.0,150.0,manuell,E6,1997.0,6.0,105.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [17]:
# delete unnamed colunm
data = data.drop(columns=["Unnamed: 13474"])

In [18]:
print(data.columns)

Index(['Brand ', 'Model', 'year of manufacture', 'Engine power (kilowatt)',
       'Engine power (Horsepower)', 'Transmission type', 'Emission group',
       'Cubic capacity', ' Number of gears', 'CO2 (g/km)', 'Tank capacity',
       'Date of general inspection', 'Mileage', 'Empty weight (kg)',
       'Permitted gross weight', 'Acceleration (0-100Km/h)', 'max_speed_kmh',
       'Region', 'Engine type', 'next general inspection', 'Color',
       'Vehicle model', 'Nber of gears', 'Nber of seats',
       'Nber previous owners', 'Number of doors', 'First_registration _car',
       'Ready to drive', 'Body style', 'Tire type', 'Rim type',
       'Rights of third parties', 'Transmission type.1', 'Accident history',
       'Sale price', 'damaged_front', 'damaged_rear', 'damaged_link_side',
       'damaged_right_side', 'damaged_interior', 'damaged_exterior',
       'accessory_missing', 'damaged_tire', 'damaged_rim', 'damaged_roof_beam',
       'damaged_mirror', 'damaged_link_door', 'damaged_right_door',
       'Nber_of_key', 'missing_winter_tires', 'major_inspection_due',
       'comfort_features', 'navigation_sytem', 'safety_features',
       'leasing_car', 'damaged_repair', 'has_winter_package',
       'has_seat_heating_front', 'has_metallic_paint',
       'space_saver_spare_wheel', 'has_headlight_washer',
       'has_foldable_front_passenger_seat', 'has_warning_light',
       'license_plate_holder', 'luggage_compartment_safety_net',
       'has_height_adjustable_passenger_seat', 'has_foldable_seat_tables',
       'has_advertising_foil'],
      dtype='object')

In [19]:
data.isnull().sum().sort_values(ascending=False)

Brand                      1
damaged_rim                1
missing_winter_tires       1
Nber_of_key                1
damaged_right_door         1
                          ..
Body style                 1
Tire type                  1
Rim type                   1
Rights of third parties    1
has_advertising_foil       1
Length: 68, dtype: int64

First of all, we split test data for later analysis

In [20]:

x=data.drop(['Sale price'], axis=1)
y=data['Sale price']

x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.2, random_state=42)
data= x_train.copy()
data['Sale price']= y_train
print(data.isnull().sum())
#print(x.info())

Brand                                   1
Model                                   1
year of manufacture                     1
Engine power (kilowatt)                 1
Engine power (Horsepower)               1
                                       ..
luggage_compartment_safety_net          1
has_height_adjustable_passenger_seat    1
has_foldable_seat_tables                1
has_advertising_foil                    1
Sale price                              1
Length: 68, dtype: int64

### Remove all missing value

In [21]:
# Remove all rows that have any missing values
data.dropna(inplace=True)

# Optional: reset index after dropping
data.reset_index(drop=True, inplace=True)

print(data.isnull().sum())

Brand                                   0
Model                                   0
year of manufacture                     0
Engine power (kilowatt)                 0
Engine power (Horsepower)               0
                                       ..
luggage_compartment_safety_net          0
has_height_adjustable_passenger_seat    0
has_foldable_seat_tables                0
has_advertising_foil                    0
Sale price                              0
Length: 68, dtype: int64

In [22]:
print(data.dtypes)

Brand                                    object
Model                                    object
year of manufacture                     float64
Engine power (kilowatt)                 float64
Engine power (Horsepower)               float64
                                         ...
luggage_compartment_safety_net          float64
has_height_adjustable_passenger_seat    float64
has_foldable_seat_tables                float64
has_advertising_foil                    float64
Sale price                              float64
Length: 68, dtype: object

In [23]:
data.info

<bound method DataFrame.info of     Brand                   Model  year of manufacture  \
0  Renault                  Kango               2021.0
1  Renault      Grand Scenic BLUE               2020.0
2  Hyundai  Nexo Fuel Cell Sports               2024.0
3  Renault      Grand Scenic BLUE               2020.0
4  Renault      Grand Scenic BLUE               2020.0
5  Renault      Grand Scenic BLUE               2020.0
6  Renault      Grand Scenic BLUE               2020.0
7  Hyundai  Nexo Fuel Cell Sports               2021.0
8  Renault      Grand Scenic BLUE               2020.0
9     Ford             Ford Focus               2018.0

   Engine power (kilowatt)  Engine power (Horsepower) Transmission type  \
0                     70.0                       95.0           manuell
1                     88.0                      120.0           manuell
2                    120.0                      163.0         automatik
3                     88.0                      120.0           manuell
4                     88.0                      120.0           manuell
5                     88.0                      120.0           manuell
6                     88.0                      120.0           manuell
7                    120.0                      163.0         Automatik
8                     88.0                      120.0           manuell
9                    110.0                      150.0           manuell

  Emission group  Cubic capacity   Number of gears  CO2 (g/km)  ...  \
0             AN          1461.0               5.0       116.0  ...
1             AN          1750.0               6.0       142.0  ...
2             AN             0.0               1.0         0.0  ...
3             AN          1750.0               6.0       142.0  ...
4             AN          1750.0               6.0       142.0  ...
5             AN          1750.0               6.0       142.0  ...
6             AN          1750.0               6.0       142.0  ...
7             AN             0.0               1.0         0.0  ...
8             AN          1750.0               6.0       142.0  ...
9             E6          1997.0               6.0       105.0  ...

   space_saver_spare_wheel has_headlight_washer  \
0                      0.0                  0.0
1                      1.0                  0.0
2                      1.0                  0.0
3                      1.0                  0.0
4                      0.0                  0.0
5                      0.0                  0.0
6                      1.0                  0.0
7                      0.0                  0.0
8                      0.0                  0.0
9                      0.0                  0.0

   has_foldable_front_passenger_seat  has_warning_light  license_plate_holder  \
0                                0.0                1.0                   0.0
1                                0.0                0.0                   1.0
2                                0.0                0.0                   0.0
3                                0.0                1.0                   1.0
4                                0.0                1.0                   1.0
5                                0.0                1.0                   1.0
6                                1.0                1.0                   1.0
7                                0.0                1.0                   1.0
8                                0.0                1.0                   1.0
9                                0.0                0.0                   0.0

   luggage_compartment_safety_net  has_height_adjustable_passenger_seat  \
0                             1.0                                   0.0
1                             1.0                                   1.0
2                             0.0                                   1.0
3                             1.0                                   0.0
4                             1.0                                   0.0
5                             1.0                                   1.0
6                             0.0                                   1.0
7                             0.0                                   0.0
8                             1.0                                   0.0
9                             0.0                                   0.0

  has_foldable_seat_tables has_advertising_foil Sale price
0                      0.0                  0.0     7100.0
1                      0.0                  0.0     7200.0
2                      0.0                  0.0     8600.0
3                      0.0                  0.0     8200.0
4                      0.0                  1.0     6600.0
5                      0.0                  0.0     8400.0
6                      0.0                  0.0     6400.0
7                      0.0                  1.0     8100.0
8                      0.0                  0.0     6200.0
9                      0.0                  0.0     6800.0

[10 rows x 68 columns]>

## Handle Duplicate Rows

In [24]:
duplicate_rows=data.duplicated()

if duplicate_rows.any():
    print(" There ist Duplicate rows")
    print(f"Number of duplicate rows: {duplicate_rows.sum()}")
    data= data.drop_duplicates()
else:
    print("No duplicate rows")
print(f"Shape of data after removing duplicates: {data.shape}")

No duplicate rows
Shape of data after removing duplicates: (10, 68)

## Numerical Sanity check

In [25]:
numerical_cols= data.select_dtypes(include=['int64','float64' ]).columns.tolist()
print(data[numerical_cols].columns)
data[numerical_cols].describe()

Index(['year of manufacture', 'Engine power (kilowatt)',
       'Engine power (Horsepower)', 'Cubic capacity', ' Number of gears',
       'CO2 (g/km)', 'Tank capacity', 'Mileage', 'Empty weight (kg)',
       'Permitted gross weight', 'Acceleration (0-100Km/h)', 'max_speed_kmh',
       'Nber of gears', 'Nber of seats', 'Nber previous owners',
       'Number of doors', 'damaged_front', 'damaged_rear', 'damaged_link_side',
       'damaged_right_side', 'damaged_interior', 'damaged_exterior',
       'accessory_missing', 'damaged_tire', 'damaged_rim', 'damaged_roof_beam',
       'damaged_mirror', 'damaged_link_door', 'damaged_right_door',
       'Nber_of_key', 'missing_winter_tires', 'major_inspection_due',
       'comfort_features', 'navigation_sytem', 'safety_features',
       'leasing_car', 'damaged_repair', 'has_winter_package',
       'has_seat_heating_front', 'has_metallic_paint',
       'space_saver_spare_wheel', 'has_headlight_washer',
       'has_foldable_front_passenger_seat', 'has_warning_light',
       'license_plate_holder', 'luggage_compartment_safety_net',
       'has_height_adjustable_passenger_seat', 'has_foldable_seat_tables',
       'has_advertising_foil', 'Sale price'],
      dtype='object')

,year of manufacture,Engine power (kilowatt),Engine power (Horsepower),Cubic capacity,Number of gears,CO2 (g/km),Tank capacity,Mileage,Empty weight (kg),Permitted gross weight,...,space_saver_spare_wheel,has_headlight_washer,has_foldable_front_passenger_seat,has_warning_light,license_plate_holder,luggage_compartment_safety_net,has_height_adjustable_passenger_seat,has_foldable_seat_tables,has_advertising_foil,Sale price
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,...,10.000000,10.0,10.000000,10.000000,10.000000,10.000000,10.000000,10.0,10.000000,10.00000
mean,2020.400000,94.800000,129.100000,1395.800000,4.900000,107.300000,75.200000,79680.000000,1668.400000,2260.000000,...,0.400000,0.0,0.100000,0.700000,0.700000,0.600000,0.400000,0.0,0.200000,7360.00000
std,1.505545,16.308144,22.098014,746.469736,2.078995,58.053711,43.206995,55157.052506,157.086813,93.808315,...,0.516398,0.0,0.316228,0.483046,0.483046,0.516398,0.516398,0.0,0.421637,889.69408
min,2018.000000,70.000000,95.000000,0.000000,1.000000,0.000000,53.000000,19061.000000,1384.000000,2050.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,6200.00000
25%,2020.000000,88.000000,120.000000,1533.250000,5.250000,107.750000,53.000000,32155.750000,1677.000000,2290.000000,...,0.000000,0.0,0.000000,0.250000,0.250000,0.000000,0.000000,0.0,0.000000,6650.00000
50%,2020.000000,88.000000,120.000000,1750.000000,6.000000,142.000000,53.000000,76873.500000,1677.000000,2290.000000,...,0.000000,0.0,0.000000,1.000000,1.000000,1.000000,0.000000,0.0,0.000000,7150.00000
75%,2020.750000,104.500000,142.500000,1750.000000,6.000000,142.000000,60.000000,126779.500000,1677.000000,2290.000000,...,1.000000,0.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.000000,8175.00000
max,2024.000000,120.000000,163.000000,1997.000000,6.000000,142.000000,157.000000,163940.000000,1889.000000,2340.000000,...,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,8600.00000

## Categorical Sanity Check

I declare all categorical variables:

    . Brand and model
    . Fuel type
    . Transmission type
    . Trim level / Equipment line
    . Vehicle condition
    . Origin,
    . Category / Vehicle type
    . Color
    . Air conditioning / Climate control 
    . Transmission
    . Drive type
    . Interior equipment / Interior design 
    . Accident history
    . Maintenance / service history 
    . Inspection status (TÜV/HU)
    . Region / city 
    . Listing duration', 'Seller type', 'Body & paint',

In [26]:
#categorical_cols= data.select_dtypes(include=['object' ]).columns.tolist()
categorical_cols = data.select_dtypes(include=['object', 'category']).columns.tolist()
print(data[categorical_cols].columns)
data[categorical_cols].describe()

print( f"Length of categorical variable: {len(categorical_cols)} ")

Index(['Brand ', 'Model', 'Transmission type', 'Emission group', 'Region',
       'Engine type', 'Color', 'Vehicle model', 'Ready to drive', 'Body style',
       'Tire type', 'Rim type', 'Rights of third parties',
       'Transmission type.1', 'Accident history'],
      dtype='object')
Length of categorical variable: 15

#### Check an index of each rows

In [27]:
def cat_checker(catIndex):
    value= np.sort(data[categorical_cols[catIndex]].unique())
    return categorical_cols[catIndex], value

cat_checker(1)

('Model',
 array([' Grand Scenic BLUE', 'Ford Focus', 'Grand Scenic BLUE', 'Kango',
        'Nexo Fuel Cell Sports'], dtype=object))

## CHECKPOINT

In [28]:

%store data
%store numerical_cols
%store categorical_cols
%store x_test 
%store y_test

Stored 'data' (DataFrame)
Stored 'numerical_cols' (list)
Stored 'categorical_cols' (list)
Stored 'x_test' (DataFrame)
Stored 'y_test' (Series)