# Data Cleaning

Step of Data Cleaning:

    1. Load Dataset
    2. Handle missing values
    3. Handle duplicate values
    4. Clean and transform Datasets
    5. store clean dataset for next workflow steps

# Librairies

In [38]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Load Data
Data ist stored as an Excel file. So, we use Pandas to load data

In [39]:
def load_data(file_path):
    data= pd.read_excel(
        file_path,
        engine='openpyxl',
        sheet_name=0
        )

    # komplett leere Spalten entfernen
    data = data.dropna(axis=1, how="all")
     # komplett leere Zeilen entfernen
    data = data.dropna(axis=0, how="all")

    return data

file_path="../Data/useCarDaten.xlsx"
import os
print("is path avaiable:",os.path.exists("../Data/useCarDaten.xlsx"))
data= load_data(file_path)
print(data.shape)
#print(data.head())
data.head(40)

is path avaiable: True
(39, 29)

,Brand,Model,year_of_manufacture,Engine_power(kilowatt),Engine_power_(Horsepower),Transmission_type,Mileage,Fueltype,nextTUV,Nber_previous_owners,...,damaged_exterior,damaged_tire,damaged_rim,damaged_roof_beam,damaged_left_door,damaged_right_door,damaged_seats,interior_dirty,damaged_carosserie,images
0,Renault,Grand Scenic BLUE,2020,88,120,manuell,121323,Diesel,2025-11-01,2,...,1,1,1,1,0,0,1,1,1,A1
1,Renault,Grand Scenic BLUE,2020,88,120,manuell,149266,Diesel,2025-11-01,2,...,0,0,0,0,0,0,1,1,1,A2
2,Renault,Grand Scenic BLUE,2020,88,120,manuell,81943,Diesel,2027-07-01,2,...,1,1,0,1,0,0,1,0,1,A3
3,Renault,Grand Scenic BLUE,2020,88,120,manuell,19457,Diesel,2027-08-01,2,...,0,0,1,0,0,0,1,1,1,A4
4,Renault,Grand Scenic BLUE,2020,88,120,manuell,72400,Diesel,2025-11-01,1,...,1,1,0,1,1,0,1,1,1,A5
5,Renault,Grand Scenic BLUE,2020,88,120,manuell,141725,Diesel,2025-08-01,2,...,0,0,0,0,0,0,1,0,1,A6
6,Ford,Ford Focus,2018,110,150,manuell,81347,Diesel,2022-02-01,1,...,0,0,0,0,1,1,0,0,0,A7
7,Renault,Grand Scenic BLUE,2020,88,120,manuell,163940,Diesel,2027-05-22,1,...,0,0,0,0,1,1,0,0,1,A8
8,Hyundai,Nexo Fuel Cell Sports,2024,120,163,automatik,37180,Hydrogen,2025-11-01,1,...,0,0,1,0,1,1,0,1,0,A9
9,Renault,Grand Scenic BLUE,2020,88,120,manuell,96607,Diesel,2025-09-01,2,...,1,1,1,1,0,0,1,1,0,A10
10,Hyundai,Nexo Fuel Cell Sports,2021,120,163,Automatik,19061,Hydrogen,2027-07-07,2,...,0,0,0,1,0,0,0,1,1,A11
11,Renault,Kango rapid Blue,2020,70,95,manuell,48170,Diesel,2026-11-01,1,...,1,0,0,0,0,0,1,0,0,A12
12,Renault,Kango rapid Blue,2021,70,95,manuell,30481,Diesel,2027-02-02,1,...,0,1,1,0,0,0,1,0,0,A13
13,Renault,Kango rapid Blue,2020,70,95,manuell,82459,Diesel,2026-12-01,2,...,1,0,0,0,0,1,0,1,0,A14
14,Renault,Kango rapid Blue,2019,70,95,manuell,77954,Diesel,2026-11-11,2,...,0,0,0,0,1,1,0,0,0,A15
15,Ford,Focus,2020,88,120,manuell,179576,Diesel,2025-09-09,1,...,1,1,0,0,1,0,0,1,0,A16
16,Renault,Grand Scenic BLUE,2020,88,120,manuell,154591,Diesel,2027-07-07,1,...,1,1,1,0,0,0,0,0,0,A17
17,Ford,Fiesta,2020,63,85,manuell,135116,Diesel,2027-07-22,1,...,1,1,1,1,1,1,1,0,1,A18
18,Renault,Grand Scenic BLUE,2019,88,120,manuell,161308,Diesel,2026-10-01,1,...,0,1,1,1,0,1,0,0,1,A19
19,Ford,Fiesta,2020,63,85,manuell,157715,Diesel,2027-07-15,1,...,1,1,1,0,0,1,1,0,1,A20
20,Renault,Traffic,2018,88,120,manuell,129262,Diesel,2025-04-01,2,...,1,1,1,1,0,1,0,1,0,A21
21,Renault,Kango rapid Blue,2021,70,95,manuell,75832,Diesel,2026-09-01,1,...,1,0,0,0,0,0,0,0,0,A22
22,Renault,Grand Scenic BLUE,2020,88,120,manuell,99619,Diesel,2026-02-01,1,...,1,1,1,0,0,0,1,0,0,A23
23,Ford,Focus,2020,110,150,automatik,178428,Diesel,2026-03-01,2,...,0,1,1,1,1,1,1,0,0,A24
24,Hyundai,Nexo Fuel Cell Sports,2022,120,163,automatik,14660,Diesel,2027-06-01,2,...,0,1,1,0,0,0,0,1,0,A25
25,Hyundai,Nexo Fuel Cell Sports,2022,120,163,automatik,35465,Diesel,2025-05-05,2,...,0,0,0,0,1,0,0,1,0,A26
26,Renault,Kango rapid Blue,2019,66,90,manuell,62880,Diesel,2026-01-01,1,...,1,1,1,0,1,0,0,0,0,A27
27,Hyundai,loniq5,2021,218,163,automatik,87012,Electronic,2026-09-01,2,...,0,0,0,0,0,0,0,1,0,A28
28,Ford,transit connect,2020,74,100,manuell,223517,Diesel,2025-08-01,1,...,1,1,1,0,1,0,1,0,0,A29
29,Hyundai,Nexo Fuel Cell Sports,2022,120,163,automatik,8896,Hydrogen,2027-05-01,1,...,0,0,0,1,0,0,1,1,0,A30
30,Hyundai,Nexo Fuel Cell Sports,2022,120,163,automatik,36640,Hydrogen,2027-05-01,2,...,0,0,0,0,0,0,1,1,0,A31
31,Renault,Grand Scenic BLUE,2018,89,120,manuell,123181,Diesel,2027-02-01,2,...,1,1,1,1,1,0,1,0,0,A32
32,Ford,Focus,2028,110,120,automatik,168732,Diesel,2026-01-01,1,...,1,1,0,1,0,1,0,0,0,A33
33,Ford,Focus,2019,88,120,manuell,171803,Diesel,2027-03-01,2,...,0,0,0,0,1,1,0,0,0,A34
34,Renault,Kango rapid Blue,2020,70,95,manuell,68389,Diesel,2026-07-01,1,...,1,0,0,0,1,0,0,0,0,A35
35,Renault,Kango rapid Blue,2020,70,95,manuell,61386,Diesel,2026-07-07,2,...,1,0,0,0,1,0,0,0,0,A36
36,Fiat,Doblo cargo,2018,74,100,manuell,202662,Diesel,2025-07-07,3,...,1,0,0,0,1,0,0,1,0,A37
37,Hyundai,Tuscson,2016,132,120,manuell,89500,Bezin,2027-03-01,2,...,0,1,1,0,0,0,0,0,1,A38
38,Ford,Fiesta,2018,103,140,manuell,62000,Bezin,2027-08-01,3,...,1,0,1,0,0,0,1,0,0,A39

In [40]:
data.shape

(39, 29)

In [41]:
data.describe()

,year_of_manufacture,Engine_power(kilowatt),Engine_power_(Horsepower),Mileage,nextTUV,Nber_previous_owners,Sale price,damaged_front,damaged_rear,damaged_left_side,...,damaged_interior,damaged_exterior,damaged_tire,damaged_rim,damaged_roof_beam,damaged_left_door,damaged_right_door,damaged_seats,interior_dirty,damaged_carosserie
count,39.000000,39.000000,39.000000,39.000000,39,39.000000,39.000000,39.000000,39.000000,39.000000,...,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000
mean,2020.153846,93.692308,121.692308,100294.435897,2026-06-24 22:46:09.230769152,1.589744,7366.410256,0.461538,0.538462,0.512821,...,0.384615,0.538462,0.487179,0.461538,0.307692,0.410256,0.307692,0.461538,0.410256,0.307692
min,2016.000000,63.000000,85.000000,8896.000000,2022-02-01 00:00:00,1.000000,3200.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2019.500000,72.000000,97.500000,61693.000000,2025-11-01 00:00:00,1.000000,6050.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2020.000000,88.000000,120.000000,87012.000000,2026-09-01 00:00:00,2.000000,6700.000000,0.000000,1.000000,1.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2020.500000,110.000000,130.000000,151928.500000,2027-05-01 00:00:00,2.000000,8150.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,2028.000000,218.000000,163.000000,223517.000000,2027-08-01 00:00:00,3.000000,17100.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
std,1.913091,27.998265,24.897848,57639.003443,NaN,0.594623,2760.358946,0.505035,0.505035,0.506370,...,0.492864,0.505035,0.506370,0.505035,0.467572,0.498310,0.467572,0.505035,0.498310,0.467572

In [42]:
# delete unnamed colunm
#data = data.drop(columns=["Unnamed: 13474"])
# data['First_registration _car'] = (
#     data['First_registration _car']
#     .astype(str)
#     .str.replace('-', '.', regex=False)
# )

# data['Date of general inspection'] = (
#     data['Date of general inspection']
#     .astype(str)
#     .str.replace('-', '.', regex=False)
# )

data['nextTUV'] = (
    data['nextTUV']
    .astype(str)
    .str.replace('00:00:00', ' ', regex=False)
)

datatime=data['nextTUV']
#(datatime)

# data['next general inspection'] = pd.to_datetime(data['next general inspection']).dt.year
# print(data['next general inspection'])

In [43]:
print(data.columns)
len(data)

Index(['Brand ', 'Model', 'year_of_manufacture', 'Engine_power(kilowatt)',
       'Engine_power_(Horsepower)', 'Transmission_type', 'Mileage', 'Fueltype',
       'nextTUV', 'Nber_previous_owners', 'Body_style', 'Tire_type',
       'Accident_history', 'Sale price', 'damaged_front', 'damaged_rear',
       'damaged_left_side', 'damaged_right_side', 'damaged_interior',
       'damaged_exterior', 'damaged_tire', 'damaged_rim', 'damaged_roof_beam',
       'damaged_left_door', 'damaged_right_door', 'damaged_seats',
       'interior_dirty', 'damaged_carosserie', 'images'],
      dtype='object')

39

In [44]:
data.isnull().sum().sort_values(ascending=False)

Brand                        0
damaged_rear                 0
damaged_carosserie           0
interior_dirty               0
damaged_seats                0
damaged_right_door           0
damaged_left_door            0
damaged_roof_beam            0
damaged_rim                  0
damaged_tire                 0
damaged_exterior             0
damaged_interior             0
damaged_right_side           0
damaged_left_side            0
damaged_front                0
Model                        0
Sale price                   0
Accident_history             0
Tire_type                    0
Body_style                   0
Nber_previous_owners         0
nextTUV                      0
Fueltype                     0
Mileage                      0
Transmission_type            0
Engine_power_(Horsepower)    0
Engine_power(kilowatt)       0
year_of_manufacture          0
images                       0
dtype: int64

First of all, we split test data for later analysis

In [45]:

x=data.drop(['Sale price'], axis=1)
y=data['Sale price']

x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.2, random_state=42)
data= x_train.copy()
data['Sale price']= y_train
print(data.isnull().sum())
#print(x.info())

Brand                        0
Model                        0
year_of_manufacture          0
Engine_power(kilowatt)       0
Engine_power_(Horsepower)    0
Transmission_type            0
Mileage                      0
Fueltype                     0
nextTUV                      0
Nber_previous_owners         0
Body_style                   0
Tire_type                    0
Accident_history             0
damaged_front                0
damaged_rear                 0
damaged_left_side            0
damaged_right_side           0
damaged_interior             0
damaged_exterior             0
damaged_tire                 0
damaged_rim                  0
damaged_roof_beam            0
damaged_left_door            0
damaged_right_door           0
damaged_seats                0
interior_dirty               0
damaged_carosserie           0
images                       0
Sale price                   0
dtype: int64

### Remove all missing value

In [46]:
# Remove all rows that have any missing values
data.dropna(inplace=True)

# Optional: reset index after dropping
data.reset_index(drop=True, inplace=True)

print(data.isnull().sum())

Brand                        0
Model                        0
year_of_manufacture          0
Engine_power(kilowatt)       0
Engine_power_(Horsepower)    0
Transmission_type            0
Mileage                      0
Fueltype                     0
nextTUV                      0
Nber_previous_owners         0
Body_style                   0
Tire_type                    0
Accident_history             0
damaged_front                0
damaged_rear                 0
damaged_left_side            0
damaged_right_side           0
damaged_interior             0
damaged_exterior             0
damaged_tire                 0
damaged_rim                  0
damaged_roof_beam            0
damaged_left_door            0
damaged_right_door           0
damaged_seats                0
interior_dirty               0
damaged_carosserie           0
images                       0
Sale price                   0
dtype: int64

In [47]:
print(data.dtypes)

Brand                        object
Model                        object
year_of_manufacture           int64
Engine_power(kilowatt)        int64
Engine_power_(Horsepower)     int64
Transmission_type            object
Mileage                       int64
Fueltype                     object
nextTUV                      object
Nber_previous_owners          int64
Body_style                   object
Tire_type                    object
Accident_history             object
damaged_front                 int64
damaged_rear                  int64
damaged_left_side             int64
damaged_right_side            int64
damaged_interior              int64
damaged_exterior              int64
damaged_tire                  int64
damaged_rim                   int64
damaged_roof_beam             int64
damaged_left_door             int64
damaged_right_door            int64
damaged_seats                 int64
interior_dirty                int64
damaged_carosserie            int64
images                       object
Sale price                    int64
dtype: object

In [48]:
#data.info

## Handle Duplicate Rows

In [49]:
duplicate_rows=data.duplicated()

if duplicate_rows.any():
    print(" There ist Duplicate rows")
    print(f"Number of duplicate rows: {duplicate_rows.sum()}")
    data= data.drop_duplicates()
else:
    print("No duplicate rows")
print(f"Shape of data after removing duplicates: {data.shape}")

No duplicate rows
Shape of data after removing duplicates: (31, 29)

## Numerical Sanity check

In [50]:
numerical_cols= data.select_dtypes(include=['int64','float64' ]).columns.tolist()
print(data[numerical_cols].columns)
data[numerical_cols].describe()

Index(['year_of_manufacture', 'Engine_power(kilowatt)',
       'Engine_power_(Horsepower)', 'Mileage', 'Nber_previous_owners',
       'damaged_front', 'damaged_rear', 'damaged_left_side',
       'damaged_right_side', 'damaged_interior', 'damaged_exterior',
       'damaged_tire', 'damaged_rim', 'damaged_roof_beam', 'damaged_left_door',
       'damaged_right_door', 'damaged_seats', 'interior_dirty',
       'damaged_carosserie', 'Sale price'],
      dtype='object')

,year_of_manufacture,Engine_power(kilowatt),Engine_power_(Horsepower),Mileage,Nber_previous_owners,damaged_front,damaged_rear,damaged_left_side,damaged_right_side,damaged_interior,damaged_exterior,damaged_tire,damaged_rim,damaged_roof_beam,damaged_left_door,damaged_right_door,damaged_seats,interior_dirty,damaged_carosserie,Sale price
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,2020.290323,90.967742,120.806452,100460.645161,1.548387,0.483871,0.548387,0.451613,0.419355,0.387097,0.548387,0.548387,0.548387,0.354839,0.354839,0.290323,0.516129,0.354839,0.354839,7241.612903
std,2.019795,19.465326,23.892006,58756.239949,0.567962,0.508001,0.505879,0.505879,0.501610,0.495138,0.505879,0.505879,0.505879,0.486373,0.486373,0.461414,0.508001,0.486373,0.486373,2318.982675
min,2016.000000,63.000000,85.000000,8896.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3200.000000
25%,2020.000000,72.000000,97.500000,54778.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6300.000000
50%,2020.000000,88.000000,120.000000,96607.000000,2.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,6600.000000
75%,2020.500000,106.500000,120.000000,151928.500000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7950.000000
max,2028.000000,132.000000,163.000000,223517.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,15000.000000

## Categorical Sanity Check

I declare all categorical variables:

    . Brand and model
    . Fuel type
    . Transmission type
    . Trim level / Equipment line
    . Vehicle condition
    . Origin,
    . Category / Vehicle type
    . Color
    . Air conditioning / Climate control 
    . Transmission
    . Drive type
    . Interior equipment / Interior design 
    . Accident history
    . Maintenance / service history 
    . Inspection status (TÜV/HU)
    . Region / city 
    . Listing duration', 'Seller type', 'Body & paint',

In [51]:
#categorical_cols= data.select_dtypes(include=['object' ]).columns.tolist()
categorical_cols = data.select_dtypes(include=['object', 'category']).columns.tolist()
print(data[categorical_cols].columns)
data[categorical_cols].describe()

print( f"Length of categorical variable: {len(categorical_cols)} ")

Index(['Brand ', 'Model', 'Transmission_type', 'Fueltype', 'nextTUV',
       'Body_style', 'Tire_type', 'Accident_history', 'images'],
      dtype='object')
Length of categorical variable: 9

#### Check an index of each rows

In [52]:
def cat_checker(catIndex):
    value= np.sort(data[categorical_cols[catIndex]].unique())
    return categorical_cols[catIndex], value

cat_checker(1)

('Model',
 array(['Fiesta', 'Focus', 'Grand Scenic BLUE', 'Kango rapid Blue',
        'Nexo Fuel Cell Sports', 'Traffic', 'Tuscson', 'transit connect'],
       dtype=object))

## CHECKPOINT

In [53]:

%store data
%store numerical_cols
%store categorical_cols
%store x_test 
%store y_test

Stored 'data' (DataFrame)
Stored 'numerical_cols' (list)
Stored 'categorical_cols' (list)
Stored 'x_test' (DataFrame)
Stored 'y_test' (Series)