# Data Cleaning

Step of Data Cleaning:

    1. Load Dataset
    2. Handle missing values
    3. Handle duplicate values
    4. Clean and transform Datasets
    5. store clean dataset for next workflow steps

# Librairies

In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Load Data
Data ist stored as an Excel file. So, we use Pandas to load data

In [6]:
def load_data(file_path):
    data= pd.read_excel(
        file_path,
        engine='openpyxl',
        sheet_name=0
        )

    # komplett leere Spalten entfernen
    data = data.dropna(axis=1, how="all")
     # komplett leere Zeilen entfernen
    data = data.dropna(axis=0, how="all")

    return data

file_path="../Data/useCarDaten.xlsx"
import os
print("is path avaiable:",os.path.exists("../Data/useCarDaten.xlsx"))
data= load_data(file_path)
print(data.shape)
#print(data.head())
data.head(7)

is path avaiable: True
(37, 68)

,Brand,Model,year of manufacture,Engine power (kilowatt),Engine power (Horsepower),Transmission type,Emission group,Cubic capacity,Number of gears,CO2 (g/km),...,has_metallic_paint,space_saver_spare_wheel,has_headlight_washer,has_foldable_front_passenger_seat,has_warning_light,license_plate_holder,luggage_compartment_safety_net,has_height_adjustable_passenger_seat,has_foldable_seat_tables,has_advertising_foil
0,Renault,Grand Scenic BLUE,2020,88,120,manuell,AN,1750,6,142,...,1,1,1,1,0,0,0,1,1,1
1,Renault,Grand Scenic BLUE,2020,88,120,manuell,AN,1750,6,142,...,1,0,0,0,1,1,1,0,0,1
2,Renault,Grand Scenic BLUE,2020,88,120,manuell,AN,1750,6,142,...,1,1,0,0,1,1,1,0,0,0
3,Renault,Grand Scenic BLUE,2020,88,120,manuell,AN,1750,6,142,...,1,0,0,0,1,1,1,0,0,0
4,Renault,Grand Scenic BLUE,2020,88,120,manuell,AN,1750,6,142,...,1,0,0,0,1,1,1,1,0,0
5,Renault,Grand Scenic BLUE,2020,88,120,manuell,AN,1750,6,142,...,1,1,0,0,0,1,1,1,0,0
6,Ford,Ford Focus,2018,110,150,manuell,E6,1997,6,105,...,0,0,0,0,0,0,0,0,0,0

In [7]:
# delete unnamed colunm
#data = data.drop(columns=["Unnamed: 13474"])
# data['First_registration _car'] = (
#     data['First_registration _car']
#     .astype(str)
#     .str.replace('-', '.', regex=False)
# )

# data['Date of general inspection'] = (
#     data['Date of general inspection']
#     .astype(str)
#     .str.replace('-', '.', regex=False)
# )

data['next general inspection'] = (
    data['next general inspection']
    .astype(str)
    .str.replace('00:00:00', ' ', regex=False)
)

datatime=data['next general inspection']
#(datatime)

# data['next general inspection'] = pd.to_datetime(data['next general inspection']).dt.year
# print(data['next general inspection'])

In [8]:
print(data.columns)

Index(['Brand ', 'Model', 'year of manufacture', 'Engine power (kilowatt)',
       'Engine power (Horsepower)', 'Transmission type', 'Emission group',
       'Cubic capacity', ' Number of gears', 'CO2 (g/km)', 'Tank capacity',
       'Date of general inspection', 'Mileage', 'Empty weight (kg)',
       'Permitted gross weight', 'Acceleration (0-100Km/h)', 'max_speed_kmh',
       'Region', 'Engine type', 'next general inspection', 'Color',
       'Vehicle model', 'Nber of gears', 'Nber of seats',
       'Nber previous owners', 'Number of doors', 'First_registration _car',
       'Ready to drive', 'Body style', 'Tire type', 'Rim type',
       'Rights of third parties', 'Transmission type2', 'Accident history',
       'Sale price', 'damaged_front', 'damaged_rear', 'damaged_link_side',
       'damaged_right_side', 'damaged_interior', 'damaged_exterior',
       'accessory_missing', 'damaged_tire', 'damaged_rim', 'damaged_roof_beam',
       'damaged_mirror', 'damaged_link_door', 'damaged_right_door',
       'Nber_of_key', 'missing_winter_tires', 'major_inspection_due',
       'comfort_features', 'navigation_sytem', 'safety_features',
       'leasing_car', 'damaged_repair', 'has_winter_package',
       'has_seat_heating_front', 'has_metallic_paint',
       'space_saver_spare_wheel', 'has_headlight_washer',
       'has_foldable_front_passenger_seat', 'has_warning_light',
       'license_plate_holder', 'luggage_compartment_safety_net',
       'has_height_adjustable_passenger_seat', 'has_foldable_seat_tables',
       'has_advertising_foil'],
      dtype='object')

In [9]:
data.isnull().sum().sort_values(ascending=False)

comfort_features           1
leasing_car                1
damaged_rim                0
Nber_of_key                0
damaged_right_door         0
                          ..
Body style                 0
Tire type                  0
Rim type                   0
Rights of third parties    0
has_advertising_foil       0
Length: 68, dtype: int64

First of all, we split test data for later analysis

In [10]:

x=data.drop(['Sale price'], axis=1)
y=data['Sale price']

x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.2, random_state=42)
data= x_train.copy()
data['Sale price']= y_train
print(data.isnull().sum())
#print(x.info())

Brand                                   0
Model                                   0
year of manufacture                     0
Engine power (kilowatt)                 0
Engine power (Horsepower)               0
                                       ..
luggage_compartment_safety_net          0
has_height_adjustable_passenger_seat    0
has_foldable_seat_tables                0
has_advertising_foil                    0
Sale price                              0
Length: 68, dtype: int64

### Remove all missing value

In [11]:
# Remove all rows that have any missing values
data.dropna(inplace=True)

# Optional: reset index after dropping
data.reset_index(drop=True, inplace=True)

print(data.isnull().sum())

Brand                                   0
Model                                   0
year of manufacture                     0
Engine power (kilowatt)                 0
Engine power (Horsepower)               0
                                       ..
luggage_compartment_safety_net          0
has_height_adjustable_passenger_seat    0
has_foldable_seat_tables                0
has_advertising_foil                    0
Sale price                              0
Length: 68, dtype: int64

In [12]:
print(data.dtypes)

Brand                                   object
Model                                   object
year of manufacture                      int64
Engine power (kilowatt)                  int64
Engine power (Horsepower)                int64
                                         ...
luggage_compartment_safety_net           int64
has_height_adjustable_passenger_seat     int64
has_foldable_seat_tables                 int64
has_advertising_foil                     int64
Sale price                               int64
Length: 68, dtype: object

In [13]:
#data.info

## Handle Duplicate Rows

In [14]:
duplicate_rows=data.duplicated()

if duplicate_rows.any():
    print(" There ist Duplicate rows")
    print(f"Number of duplicate rows: {duplicate_rows.sum()}")
    data= data.drop_duplicates()
else:
    print("No duplicate rows")
print(f"Shape of data after removing duplicates: {data.shape}")

No duplicate rows
Shape of data after removing duplicates: (27, 68)

## Numerical Sanity check

In [15]:
numerical_cols= data.select_dtypes(include=['int64','float64' ]).columns.tolist()
print(data[numerical_cols].columns)
data[numerical_cols].describe()

Index(['year of manufacture', 'Engine power (kilowatt)',
       'Engine power (Horsepower)', 'Cubic capacity', ' Number of gears',
       'CO2 (g/km)', 'Tank capacity', 'Mileage', 'Empty weight (kg)',
       'Permitted gross weight', 'Acceleration (0-100Km/h)', 'max_speed_kmh',
       'Nber of gears', 'Nber of seats', 'Nber previous owners',
       'Number of doors', 'damaged_front', 'damaged_rear', 'damaged_link_side',
       'damaged_right_side', 'damaged_interior', 'damaged_exterior',
       'accessory_missing', 'damaged_tire', 'damaged_rim', 'damaged_roof_beam',
       'damaged_mirror', 'damaged_link_door', 'damaged_right_door',
       'Nber_of_key', 'missing_winter_tires', 'major_inspection_due',
       'comfort_features', 'navigation_sytem', 'safety_features',
       'leasing_car', 'damaged_repair', 'has_winter_package',
       'has_seat_heating_front', 'has_metallic_paint',
       'space_saver_spare_wheel', 'has_headlight_washer',
       'has_foldable_front_passenger_seat', 'has_warning_light',
       'license_plate_holder', 'luggage_compartment_safety_net',
       'has_height_adjustable_passenger_seat', 'has_foldable_seat_tables',
       'has_advertising_foil', 'Sale price'],
      dtype='object')

,year of manufacture,Engine power (kilowatt),Engine power (Horsepower),Cubic capacity,Number of gears,CO2 (g/km),Tank capacity,Mileage,Empty weight (kg),Permitted gross weight,...,space_saver_spare_wheel,has_headlight_washer,has_foldable_front_passenger_seat,has_warning_light,license_plate_holder,luggage_compartment_safety_net,has_height_adjustable_passenger_seat,has_foldable_seat_tables,has_advertising_foil,Sale price
count,27.000000,27.00000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,...,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000
mean,2020.481481,95.37037,123.703704,1351.444444,5.185185,96.740741,78.222222,105913.222222,1694.037037,2217.222222,...,0.333333,0.074074,0.259259,0.481481,0.407407,0.296296,0.296296,0.074074,0.259259,7118.518519
std,1.928937,29.29577,22.616901,673.609527,1.861287,64.996800,43.329980,59451.357142,281.821067,144.270935,...,0.480384,0.266880,0.446576,0.509175,0.500712,0.465322,0.465322,0.266880,0.446576,2469.512103
min,2018.000000,70.00000,95.000000,0.000000,1.000000,0.000000,47.000000,14660.000000,1384.000000,1800.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3200.000000
25%,2020.000000,88.00000,120.000000,1461.000000,5.000000,0.000000,53.000000,58279.500000,1577.500000,2130.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6050.000000
50%,2020.000000,88.00000,120.000000,1598.000000,6.000000,140.000000,53.000000,99619.000000,1677.000000,2290.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6600.000000
75%,2021.000000,99.50000,120.000000,1750.000000,6.000000,142.000000,70.000000,157949.500000,1783.000000,2290.000000,...,1.000000,0.000000,0.500000,1.000000,1.000000,1.000000,1.000000,0.000000,0.500000,7950.000000
max,2028.000000,218.00000,163.000000,1997.000000,8.000000,170.000000,157.000000,223517.000000,2800.000000,2340.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,17100.000000

## Categorical Sanity Check

I declare all categorical variables:

    . Brand and model
    . Fuel type
    . Transmission type
    . Trim level / Equipment line
    . Vehicle condition
    . Origin,
    . Category / Vehicle type
    . Color
    . Air conditioning / Climate control 
    . Transmission
    . Drive type
    . Interior equipment / Interior design 
    . Accident history
    . Maintenance / service history 
    . Inspection status (TÜV/HU)
    . Region / city 
    . Listing duration', 'Seller type', 'Body & paint',

In [16]:
#categorical_cols= data.select_dtypes(include=['object' ]).columns.tolist()
categorical_cols = data.select_dtypes(include=['object', 'category']).columns.tolist()
print(data[categorical_cols].columns)
data[categorical_cols].describe()

print( f"Length of categorical variable: {len(categorical_cols)} ")

Index(['Brand ', 'Model', 'Transmission type', 'Emission group', 'Region',
       'Engine type', 'next general inspection', 'Color', 'Vehicle model',
       'Ready to drive', 'Body style', 'Tire type', 'Rim type',
       'Rights of third parties', 'Transmission type2', 'Accident history'],
      dtype='object')
Length of categorical variable: 16

#### Check an index of each rows

In [17]:
def cat_checker(catIndex):
    value= np.sort(data[categorical_cols[catIndex]].unique())
    return categorical_cols[catIndex], value

cat_checker(1)

('Model',
 array(['Ford Focus', 'Grand Scenic BLUE', 'Kango rapid Blue',
        'Nexo Fuel Cell Sports', 'Traffic', 'loniq5', 'transit connect'],
       dtype=object))

## CHECKPOINT

In [18]:

%store data
%store numerical_cols
%store categorical_cols
%store x_test 
%store y_test

Stored 'data' (DataFrame)
Stored 'numerical_cols' (list)
Stored 'categorical_cols' (list)
Stored 'x_test' (DataFrame)
Stored 'y_test' (Series)